export const ALL_SURAHS = [
  { number: 1, englishName: "Al-Fatihah", arabicName: "الفاتحة", translatedName: "The Opening", versesCount: 7, revelationPlace: "Makkah" },
  { number: 2, englishName: "Al-Baqarah", arabicName: "البقرة", translatedName: "The Cow", versesCount: 286, revelationPlace: "Madinah" },
  { number: 3, englishName: "Ali 'Imran", arabicName: "آل عمران", translatedName: "Family of Imran", versesCount: 200, revelationPlace: "Madinah" },
  { number: 4, englishName: "An-Nisa", arabicName: "النساء", translatedName: "The Women", versesCount: 176, revelationPlace: "Madinah" },
  { number: 5, englishName: "Al-Ma'idah", arabicName: "المائدة", translatedName: "The Table Spread", versesCount: 120, revelationPlace: "Madinah" },
  { number: 6, englishName: "Al-An'am", arabicName: "الأنعام", translatedName: "The Cattle", versesCount: 165, revelationPlace: "Makkah" },
  { number: 7, englishName: "Al-A'raf", arabicName: "الأعراف", translatedName: "The Heights", versesCount: 206, revelationPlace: "Makkah" },
  { number: 8, englishName: "Al-Anfal", arabicName: "الأنفال", translatedName: "The Spoils of War", versesCount: 75, revelationPlace: "Madinah" },
  { number: 9, englishName: "At-Tawbah", arabicName: "التوبة", translatedName: "The Repentance", versesCount: 129, revelationPlace: "Madinah" },
  { number: 10, englishName: "Yunus", arabicName: "يونس", translatedName: "Jonah", versesCount: 109, revelationPlace: "Makkah" },
  { number: 11, englishName: "Hud", arabicName: "هود", translatedName: "Hud", versesCount: 123, revelationPlace: "Makkah" },
  { number: 12, englishName: "Yusuf", arabicName: "يوسف", translatedName: "Joseph", versesCount: 111, revelationPlace: "Makkah" },
  { number: 13, englishName: "Ar-Ra'd", arabicName: "الرعد", translatedName: "The Thunder", versesCount: 43, revelationPlace: "Madinah" },
  { number: 14, englishName: "Ibrahim", arabicName: "ابراهيم", translatedName: "Abraham", versesCount: 52, revelationPlace: "Makkah" },
  { number: 15, englishName: "Al-Hijr", arabicName: "الحجر", translatedName: "The Rocky Tract", versesCount: 99, revelationPlace: "Makkah" },
  { number: 16, englishName: "An-Nahl", arabicName: "النحل", translatedName: "The Bee", versesCount: 128, revelationPlace: "Makkah" },
  { number: 17, englishName: "Al-Isra", arabicName: "الإسراء", translatedName: "The Night Journey", versesCount: 111, revelationPlace: "Makkah" },
  { number: 18, englishName: "Al-Kahf", arabicName: "الكهف", translatedName: "The Cave", versesCount: 110, revelationPlace: "Makkah" },
  { number: 19, englishName: "Maryam", arabicName: "مريم", translatedName: "Mary", versesCount: 98, revelationPlace: "Makkah" },
  { number: 20, englishName: "Taha", arabicName: "طه", translatedName: "Ta-Ha", versesCount: 135, revelationPlace: "Makkah" },
  { number: 21, englishName: "Al-Anbiya", arabicName: "الأنبياء", translatedName: "The Prophets", versesCount: 112, revelationPlace: "Makkah" },
  { number: 22, englishName: "Al-Hajj", arabicName: "الحج", translatedName: "The Pilgrimage", versesCount: 78, revelationPlace: "Madinah" },
  { number: 23, englishName: "Al-Mu'minun", arabicName: "المؤمنون", translatedName: "The Believers", versesCount: 118, revelationPlace: "Makkah" },
  { number: 24, englishName: "An-Nur", arabicName: "النور", translatedName: "The Light", versesCount: 64, revelationPlace: "Madinah" },
  { number: 25, englishName: "Al-Furqan", arabicName: "الفرقان", translatedName: "The Criterion", versesCount: 77, revelationPlace: "Makkah" },
  { number: 26, englishName: "Ash-Shu'ara", arabicName: "الشعراء", translatedName: "The Poets", versesCount: 227, revelationPlace: "Makkah" },
  { number: 27, englishName: "An-Naml", arabicName: "النمل", translatedName: "The Ant", versesCount: 93, revelationPlace: "Makkah" },
  { number: 28, englishName: "Al-Qasas", arabicName: "القصص", translatedName: "The Stories", versesCount: 88, revelationPlace: "Makkah" },
  { number: 29, englishName: "Al-'Ankabut", arabicName: "العنكبوت", translatedName: "The Spider", versesCount: 69, revelationPlace: "Makkah" },
  { number: 30, englishName: "Ar-Rum", arabicName: "الروم", translatedName: "The Romans", versesCount: 60, revelationPlace: "Makkah" },
  { number: 31, englishName: "Luqman", arabicName: "لقمان", translatedName: "Luqman", versesCount: 34, revelationPlace: "Makkah" },
  { number: 32, englishName: "As-Sajdah", arabicName: "السجدة", translatedName: "The Prostration", versesCount: 30, revelationPlace: "Makkah" },
  { number: 33, englishName: "Al-Ahzab", arabicName: "الأحزاب", translatedName: "The Combined Forces", versesCount: 73, revelationPlace: "Madinah" },
  { number: 34, englishName: "Saba", arabicName: "سبإ", translatedName: "Sheba", versesCount: 54, revelationPlace: "Makkah" },
  { number: 35, englishName: "Fatir", arabicName: "فاطر", translatedName: "Originator", versesCount: 45, revelationPlace: "Makkah" },
  { number: 36, englishName: "Ya-Sin", arabicName: "يس", translatedName: "Ya Sin", versesCount: 83, revelationPlace: "Makkah" },
  { number: 37, englishName: "As-Saffat", arabicName: "الصافات", translatedName: "Those who set the Ranks", versesCount: 182, revelationPlace: "Makkah" },
  { number: 38, englishName: "Sad", arabicName: "ص", translatedName: "The Letter Sad", versesCount: 88, revelationPlace: "Makkah" },
  { number: 39, englishName: "Az-Zumar", arabicName: "الزمر", translatedName: "The Troops", versesCount: 75, revelationPlace: "Makkah" },
  { number: 40, englishName: "Ghafir", arabicName: "غافر", translatedName: "The Forgiver", versesCount: 85, revelationPlace: "Makkah" },
  { number: 41, englishName: "Fussilat", arabicName: "فصلت", translatedName: "Explained in Detail", versesCount: 54, revelationPlace: "Makkah" },
  { number: 42, englishName: "Ash-Shuraa", arabicName: "الشورى", translatedName: "The Consultation", versesCount: 53, revelationPlace: "Makkah" },
  { number: 43, englishName: "Az-Zukhruf", arabicName: "الزخرف", translatedName: "The Ornaments of Gold", versesCount: 89, revelationPlace: "Makkah" },
  { number: 44, englishName: "Ad-Dukhan", arabicName: "الدخان", translatedName: "The Smoke", versesCount: 59, revelationPlace: "Makkah" },
  { number: 45, englishName: "Al-Jathiyah", arabicName: "الجاثية", translatedName: "The Crouching", versesCount: 37, revelationPlace: "Makkah" },
  { number: 46, englishName: "Al-Ahqaf", arabicName: "الأحقاف", translatedName: "The Wind-Curved Sandhills", versesCount: 35, revelationPlace: "Makkah" },
  { number: 47, englishName: "Muhammad", arabicName: "محمد", translatedName: "Muhammad", versesCount: 38, revelationPlace: "Madinah" },
  { number: 48, englishName: "Al-Fath", arabicName: "الفتح", translatedName: "The Victory", versesCount: 29, revelationPlace: "Madinah" },
  { number: 49, englishName: "Al-Hujurat", arabicName: "الحجرات", translatedName: "The Rooms", versesCount: 18, revelationPlace: "Madinah" },
  { number: 50, englishName: "Qaf", arabicName: "ق", translatedName: "The Letter Qaf", versesCount: 45, revelationPlace: "Makkah" },
  { number: 51, englishName: "Adh-Dhariyat", arabicName: "الذاريات", translatedName: "The Winnowing Winds", versesCount: 60, revelationPlace: "Makkah" },
  { number: 52, englishName: "At-Tur", arabicName: "الطور", translatedName: "The Mount", versesCount: 49, revelationPlace: "Makkah" },
  { number: 53, englishName: "An-Najm", arabicName: "النجم", translatedName: "The Star", versesCount: 62, revelationPlace: "Makkah" },
  { number: 54, englishName: "Al-Qamar", arabicName: "القمر", translatedName: "The Moon", versesCount: 55, revelationPlace: "Makkah" },
  { number: 55, englishName: "Ar-Rahman", arabicName: "الرحمن", translatedName: "The Beneficent", versesCount: 78, revelationPlace: "Madinah" },
  { number: 56, englishName: "Al-Waqi'ah", arabicName: "الواقعة", translatedName: "The Inevitable", versesCount: 96, revelationPlace: "Makkah" },
  { number: 57, englishName: "Al-Hadid", arabicName: "الحديد", translatedName: "The Iron", versesCount: 29, revelationPlace: "Madinah" },
  { number: 58, englishName: "Al-Mujadila", arabicName: "المجادلة", translatedName: "The Pleading Woman", versesCount: 22, revelationPlace: "Madinah" },
  { number: 59, englishName: "Al-Hashr", arabicName: "الحشر", translatedName: "The Exile", versesCount: 24, revelationPlace: "Madinah" },
  { number: 60, englishName: "Al-Mumtahanah", arabicName: "الممتحنة", translatedName: "She that is to be examined", versesCount: 13, revelationPlace: "Madinah" },
  { number: 61, englishName: "As-Saf", arabicName: "الصف", translatedName: "The Ranks", versesCount: 14, revelationPlace: "Madinah" },
  { number: 62, englishName: "Al-Jumu'ah", arabicName: "الجمعة", translatedName: "The Congregation", versesCount: 11, revelationPlace: "Madinah" },
  { number: 63, englishName: "Al-Munafiqun", arabicName: "المنافقون", translatedName: "The Hypocrites", versesCount: 11, revelationPlace: "Madinah" },
  { number: 64, englishName: "At-Taghabun", arabicName: "التغابن", translatedName: "The Mutual Disillusion", versesCount: 18, revelationPlace: "Madinah" },
  { number: 65, englishName: "At-Talaq", arabicName: "الطلاق", translatedName: "The Divorce", versesCount: 12, revelationPlace: "Madinah" },
  { number: 66, englishName: "At-Tahrim", arabicName: "التحريم", translatedName: "The Prohibition", versesCount: 12, revelationPlace: "Madinah" },
  { number: 67, englishName: "Al-Mulk", arabicName: "الملك", translatedName: "The Sovereignty", versesCount: 30, revelationPlace: "Makkah" },
  { number: 68, englishName: "Al-Qalam", arabicName: "القلم", translatedName: "The Pen", versesCount: 52, revelationPlace: "Makkah" },
  { number: 69, englishName: "Al-Haqqah", arabicName: "الحاقة", translatedName: "The Reality", versesCount: 52, revelationPlace: "Makkah" },
  { number: 70, englishName: "Al-Ma'arij", arabicName: "المعارج", translatedName: "The Ascending Stairways", versesCount: 44, revelationPlace: "Makkah" },
  { number: 71, englishName: "Nuh", arabicName: "نوح", translatedName: "Noah", versesCount: 28, revelationPlace: "Makkah" },
  { number: 72, englishName: "Al-Jinn", arabicName: "الجن", translatedName: "The Jinn", versesCount: 28, revelationPlace: "Makkah" },
  { number: 73, englishName: "Al-Muzzammil", arabicName: "المزمل", translatedName: "The Enshrouded One", versesCount: 20, revelationPlace: "Makkah" },
  { number: 74, englishName: "Al-Muddaththir", arabicName: "المدثر", translatedName: "The Cloaked One", versesCount: 56, revelationPlace: "Makkah" },
  { number: 75, englishName: "Al-Qiyamah", arabicName: "القيامة", translatedName: "The Resurrection", versesCount: 40, revelationPlace: "Makkah" },
  { number: 76, englishName: "Al-Insan", arabicName: "الانسان", translatedName: "The Man", versesCount: 31, revelationPlace: "Madinah" },
  { number: 77, englishName: "Al-Mursalat", arabicName: "المرسلات", translatedName: "The Emissaries", versesCount: 50, revelationPlace: "Makkah" },
  { number: 78, englishName: "An-Naba", arabicName: "النبإ", translatedName: "The Tidings", versesCount: 40, revelationPlace: "Makkah" },
  { number: 79, englishName: "An-Nazi'at", arabicName: "النازعات", translatedName: "Those who drag forth", versesCount: 46, revelationPlace: "Makkah" },
  { number: 80, englishName: "'Abasa", arabicName: "عبس", translatedName: "He Frowned", versesCount: 42, revelationPlace: "Makkah" },
  { number: 81, englishName: "At-Takwir", arabicName: "التكوير", translatedName: "The Overthrowing", versesCount: 29, revelationPlace: "Makkah" },
  { number: 82, englishName: "Al-Infitar", arabicName: "الإنفطار", translatedName: "The Cleaving", versesCount: 19, revelationPlace: "Makkah" },
  { number: 83, englishName: "Al-Mutaffifin", arabicName: "المطففين", translatedName: "The Defrauding", versesCount: 36, revelationPlace: "Makkah" },
  { number: 84, englishName: "Al-Inshiqaq", arabicName: "الإنشقاق", translatedName: "The Splitting Open", versesCount: 25, revelationPlace: "Makkah" },
  { number: 85, englishName: "Al-Buruj", arabicName: "البروج", translatedName: "The Mansions of the Stars", versesCount: 22, revelationPlace: "Makkah" },
  { number: 86, englishName: "At-Tariq", arabicName: "الطارق", translatedName: "The Nightcommer", versesCount: 17, revelationPlace: "Makkah" },
  { number: 87, englishName: "Al-A'la", arabicName: "الأعلى", translatedName: "The Most High", versesCount: 19, revelationPlace: "Makkah" },
  { number: 88, englishName: "Al-Ghashiyah", arabicName: "الغاشية", translatedName: "The Overwhelming", versesCount: 26, revelationPlace: "Makkah" },
  { number: 89, englishName: "Al-Fajr", arabicName: "الفجر", translatedName: "The Dawn", versesCount: 30, revelationPlace: "Makkah" },
  { number: 90, englishName: "Al-Balad", arabicName: "البلد", translatedName: "The City", versesCount: 20, revelationPlace: "Makkah" },
  { number: 91, englishName: "Ash-Shams", arabicName: "الشمس", translatedName: "The Sun", versesCount: 15, revelationPlace: "Makkah" },
  { number: 92, englishName: "Al-Layl", arabicName: "الليل", translatedName: "The Night", versesCount: 21, revelationPlace: "Makkah" },
  { number: 93, englishName: "Ad-Duhaa", arabicName: "الضحى", translatedName: "The Morning Hours", versesCount: 11, revelationPlace: "Makkah" },
  { number: 94, englishName: "Ash-Sharh", arabicName: "الشرح", translatedName: "The Relief", versesCount: 8, revelationPlace: "Makkah" },
  { number: 95, englishName: "At-Tin", arabicName: "التين", translatedName: "The Fig", versesCount: 8, revelationPlace: "Makkah" },
  { number: 96, englishName: "Al-'Alaq", arabicName: "العلق", translatedName: "The Clot", versesCount: 19, revelationPlace: "Makkah" },
  { number: 97, englishName: "Al-Qadr", arabicName: "القدر", translatedName: "The Power", versesCount: 5, revelationPlace: "Makkah" },
  { number: 98, englishName: "Al-Bayyinah", arabicName: "البينة", translatedName: "The Clear Proof", versesCount: 8, revelationPlace: "Madinah" },
  { number: 99, englishName: "Az-Zalzalah", arabicName: "الزلزلة", translatedName: "The Earthquake", versesCount: 8, revelationPlace: "Madinah" },
  { number: 100, englishName: "Al-'Adiyat", arabicName: "العاديات", translatedName: "The Courser", versesCount: 11, revelationPlace: "Makkah" },
  { number: 101, englishName: "Al-Qari'ah", arabicName: "القارعة", translatedName: "The Calamity", versesCount: 11, revelationPlace: "Makkah" },
  { number: 102, englishName: "At-Takathur", arabicName: "التكاثر", translatedName: "The Rivalry in world increase", versesCount: 8, revelationPlace: "Makkah" },
  { number: 103, englishName: "Al-'Asr", arabicName: "العصر", translatedName: "The Declining Day", versesCount: 3, revelationPlace: "Makkah" },
  { number: 104, englishName: "Al-Humazah", arabicName: "الهمزة", translatedName: "The Traducer", versesCount: 9, revelationPlace: "Makkah" },
  { number: 105, englishName: "Al-Fil", arabicName: "الفيل", translatedName: "The Elephant", versesCount: 5, revelationPlace: "Makkah" },
  { number: 106, englishName: "Quraysh", arabicName: "قريش", translatedName: "Quraysh", versesCount: 4, revelationPlace: "Makkah" },
  { number: 107, englishName: "Al-Ma'un", arabicName: "الماعون", translatedName: "The Small Kindnesses", versesCount: 7, revelationPlace: "Makkah" },
  { number: 108, englishName: "Al-Kawthar", arabicName: "الكوثر", translatedName: "The Abundance", versesCount: 3, revelationPlace: "Makkah" },
  { number: 109, englishName: "Al-Kafirun", arabicName: "الكافرون", translatedName: "The Disbelievers", versesCount: 6, revelationPlace: "Makkah" },
  { number: 110, englishName: "An-Nasr", arabicName: "النصر", translatedName: "The Divine Support", versesCount: 3, revelationPlace: "Madinah" },
  { number: 111, englishName: "Al-Masad", arabicName: "المسد", translatedName: "The Palm Fiber", versesCount: 5, revelationPlace: "Makkah" },
  { number: 112, englishName: "Al-Ikhlas", arabicName: "الإخلاص", translatedName: "The Sincerity", versesCount: 4, revelationPlace: "Makkah" },
  { number: 113, englishName: "Al-Falaq", arabicName: "الفلق", translatedName: "The Daybreak", versesCount: 5, revelationPlace: "Makkah" },
  { number: 114, englishName: "An-Nas", arabicName: "الناس", translatedName: "Mankind", versesCount: 6, revelationPlace: "Makkah" },
];
