name: Namaz Cron Trigger

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes (GitHub's minimum for free scheduled workflows)
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s "https://quran-application-with-next-js-seh2.vercel.app/api/push/send?bypass=true"
